# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb6472854beedf17ccbd4bc4302f4d64ee9e2b30c98615e56235d59e03ce86ff3647cfd96a7a11b1c3cefa5cf29c500c914f5e0dd306c54311cd255160139b3b

test:
  secret_key_base: dabf538f1252a6f23689a3bdfa2f3f966769979e9eae6c0c8884a1a7107e5cd686780c3b3c910807b7debfebe78f40cf885f09702804d8cb6c4fa3aa1ac41993


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
